// <auto-generated />
using LeL.ExpenseTracker.Api.Domain;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LeL.ExpenseTracker.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddExpenseCategoryData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var categories = new[]
            {
                ((int)ExpenseCategoryType.FoodAndDining, "Food & Dining", "Restaurants, groceries, and meal deliveries"),
                ((int)ExpenseCategoryType.Transportation, "Transportation", "Public transit, fuel, ride sharing, and vehicle maintenance"),
                ((int)ExpenseCategoryType.Housing, "Housing", "Rent, mortgage, and home repairs"),
                ((int)ExpenseCategoryType.Utilities, "Utilities", "Electricity, water, internet, and phone bills"),
                ((int)ExpenseCategoryType.Healthcare, "Healthcare", "Medical visits, medications, and health insurance"),
                ((int)ExpenseCategoryType.Entertainment, "Entertainment", "Movies, games, concerts, and subscription services"),
                ((int)ExpenseCategoryType.Shopping, "Shopping", "Clothing, electronics, and household items"),
                ((int)ExpenseCategoryType.Education, "Education", "Tuition, books, and courses"),
                ((int)ExpenseCategoryType.Travel, "Travel", "Hotels, flights, and vacation expenses"),
                ((int)ExpenseCategoryType.Business, "Business", "Work-related expenses and professional services")
            };

            foreach (var (id, name, description) in categories)
            {
                migrationBuilder.InsertData(
                    table: "ExpenseCategories",
                    columns: new[] { "Id", "Name", "Description" },
                    values: new object[] { id, name, description });
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "ExpenseCategories",
                keyColumn: "Id",
                keyValues: new object[] {
                    (int)ExpenseCategoryType.FoodAndDining,
                    (int)ExpenseCategoryType.Transportation,
                    (int)ExpenseCategoryType.Housing,
                    (int)ExpenseCategoryType.Utilities,
                    (int)ExpenseCategoryType.Healthcare,
                    (int)ExpenseCategoryType.Entertainment,
                    (int)ExpenseCategoryType.Shopping,
                    (int)ExpenseCategoryType.Education,
                    (int)ExpenseCategoryType.Travel,
                    (int)ExpenseCategoryType.Business
                });
        }
    }
}
